services:
  - type: web
    name: kokitos-pdv
    runtime: node
    region: ohio
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3000
